service: testing-api-key
frameworkVersion: '2'
useDotenv: true
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'local'}
  apiGateway:
    apiKeys:
      - clientId2
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /users/create
          method: get
          private: true
          resp: json
          cors: true